package com.springone.entity;
// Generated Aug 6, 2013 11:57:10 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRole implements java.io.Serializable {

    private UserRoleId id;
    private User user;

    public UserRole() {
    }

    public UserRole(UserRoleId id, User user) {
        this.id = id;
        this.user = user;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "userId", column =
                @Column(name = "user_id", nullable = false)),
        @AttributeOverride(name = "role", column =
                @Column(name = "role", nullable = false, length = 50))})
    public UserRoleId getId() {
        return this.id;
    }

    public void setId(UserRoleId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
