package com.springone.entity;
// Generated Aug 6, 2013 11:57:10 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserSnsId generated by hbm2java
 */
@Embeddable
public class UserSnsId implements java.io.Serializable {

    private String snsId;
    private byte snsType;

    public UserSnsId() {
    }

    public UserSnsId(String snsId, byte snsType) {
        this.snsId = snsId;
        this.snsType = snsType;
    }

    @Column(name = "sns_id", nullable = false)
    public String getSnsId() {
        return this.snsId;
    }

    public void setSnsId(String snsId) {
        this.snsId = snsId;
    }

    @Column(name = "sns_type", nullable = false)
    public byte getSnsType() {
        return this.snsType;
    }

    public void setSnsType(byte snsType) {
        this.snsType = snsType;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UserSnsId)) {
            return false;
        }
        UserSnsId castOther = (UserSnsId) other;

        return ((this.getSnsId() == castOther.getSnsId()) || (this.getSnsId() != null && castOther.getSnsId() != null && this.getSnsId().equals(castOther.getSnsId())))
                && (this.getSnsType() == castOther.getSnsType());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getSnsId() == null ? 0 : this.getSnsId().hashCode());
        result = 37 * result + this.getSnsType();
        return result;
    }
}
